// Casalborgone Zona unica (SETA): Corso Beltramo, Corso Carlo e Siro Bongiovanni, Corso Giovanni Zucco, Corso Vittorio Emanuele II, Piazza Bruna, Piazza Carlo Bruna, Piazza Cavour, Piazza SAN MARTINO, Piazza Statuto, Piazza Vittorio Emanuele II, Regione Borgione, Regione Roncola, Strada ANDORNA, Strada Audino, Strada Aurelia, Strada Balestra, Strada Baudina, Strada Berteu, Strada Boccardo, Strada Bongallo, Strada Borganino, Strada Brichetto, Strada Caola, Strada Ceriaglio, Strada Cerro, Strada CERTO, Strada Civignola, Strada Compostella, Strada Faitaria Cairola, Strada Fiore, Strada Foei, Strada Gallina, Strada Gianardo, Strada Gianella, Strada Giangranda, Strada Giardina, Strada Ginoberta, Strada Gora, Strada Luigi Macario, Strada Maruia, Strada Moncalvo, Strada Mongallo, Strada Nin, Strada Priaglia, Strada Prin, Strada Randona, Strada Ritana, Strada Rovere, Strada San Giuseppe, Strada San Martino, Strada San Pietro, Strada San Rocco, Strada Santa Maria, Strada Serraglio, Strada SP101, Strada SP102, Strada SP103, Strada SP97, Strada SS458, Strada Tetti Chiapino, Strada Val Berzano, Strada Val Caramellini, Strada Val Chiapini, Strada Val Ferro, Strada Val Frascherina, Strada Val Gobbo, Strada Val Scagno, Via Asilo, Via Aurelia, Via Avvocato Carlo Crosa, Via Battaglia, Via Broglia, Via Ca Nova, Via Carlo Alberto, Via CAVALIER ANDREA GAIATO, Via Ceraglio, Via Chiapini, Via Conte Antonio Gioppi, Via Croce Pietra, Via Don Bosco, Via Fornace, Via Garibaldi, Via Inesistente, Via Lanfranchi, Via Leona, Via Losa, Via Mazzini, Via Nobiei, Via Palestro, Via Perrucchetti, Via Pessione, Via Radicati, Via Regina Elena, Via Regina Margherita, Via Roma, Via Sant'Antonino, Via Scalassa, Via Soliti, Via Umberto I, Via Valfre, Via Vittorio Emanuele II
// Anno 2027 — solo dati; struct e helper in docs/calendar.h
// Mappa cassonetti: 0 Carta, 1 Organico, 2 Indifferenziata, 3 Plastica, 4 Verde, 5 Vetro
// Lista ORDINATA (YYYYMMDD) per ricerca binaria.

  {2027, 1, 2, 1},  // 02/01/2027 Organico
  {2027, 1, 3, 1},  // 03/01/2027 Organico
  {2027, 1, 6, 0},  // 06/01/2027 Carta
  {2027, 1, 9, 1},  // 09/01/2027 Organico
  {2027, 1, 9, 2},  // 09/01/2027 Indifferenziata
