// Gassino Torinese Zona 4 (SETA): LOCALITA' SERRAPONE, STRADA AMBOSSA, STRADA BARERE, STRADA BOCCHIOLA, STRADA COLLINA SERRA, STRADA COMUNALE DA PAVAROLO A BARDASSANO, STRADA DEI PINI, STRADA DELLA TRINITA', STRADA GASSINO BARDASSANO, STRADA M. CAUDANA, STRADA SAN TOMMASO, STRADA SCIOLZE, STRADA VAL PAIRONE, STRADA VAL VILLATA, STRADA VALLE FEI, STRADA VALLE MASSA, STRADA VALLE PALLERA, VIA A. PACINOTTI, VIA A. VOLTA, VIA BARDASSANO CENTRO, VIA BRICCO, VIA L. BOLLINO, VIA L. BORIONE, VIA MONTE MUCRONE, VIA MONTE ROSA, VIA MONVISO, VIA SAN DOMENICO SAVIO, VIA SAN FRANCESCO D'ASSISI, VIA SAN GIOVANNI BOSCO, VIA SAN GIUSEPPE, VIA SAN GIUSEPPE COTTOLENGO, VIA SAN GRATO (Comune di Castiglione), corrisponde a VIA SAN, GIUSEPPE 14, Gassino, VIA SAN MAURIZIO, VIA SANTA CECILIA, VIA SANTA CHIARA, VIA SANTA LUCIA, VIA SANTA RITA, VIA SANTA TERESA, VIA SANT'AGOSTINO, VIA SANT'ANDREA, VIALE CATULLO, VIALE OVIDIO, VIALE VIRGILIO, VICOLO DELLA CONSOLATA, VICOLO PIAVE
// Anno 2027 — solo dati; struct e helper in docs/calendar.h
// Mappa cassonetti: 0 Carta, 1 Organico, 2 Indifferenziata, 3 Plastica, 4 Verde, 5 Vetro
// Lista ORDINATA (YYYYMMDD) per ricerca binaria.

  {2027, 1, 4, 1},  // 04/01/2027 Organico
  {2027, 1, 4, 3},  // 04/01/2027 Plastica
  {2027, 1, 5, 1},  // 05/01/2027 Organico
  {2027, 1, 5, 3},  // 05/01/2027 Plastica
  {2027, 1, 7, 1},  // 07/01/2027 Organico
  {2027, 1, 7, 2},  // 07/01/2027 Indifferenziata
  {2027, 1, 8, 5},  // 08/01/2027 Vetro
  {2027, 1, 9, 5},  // 09/01/2027 Vetro
